### PR TITLE
Removed hardcode from protokube logic. Fixes #15.

### LINKED ISSUE #15: protokube/vsphere_volume should get actual device details
Now information like EtcdNodeName/EtcdClusterName and local device name are hard-coded:
https://github.com/vmware/kops/blob/vsphere-develop/protokube/pkg/protokube/vsphere_volume.go#L30

Need to get these information from actual setting.

### PR DESCRIPTION
**Pull request by prashima**
Changes:
1. Populating volume metadata based on actual zone name passed in 'kops cluster create' command.
2. Updated protokube code to use volume metadata and create volume and etcd cluster spec.

Testing:
- Ran 'make ci'

- Successfully deployed cluster with following command, please note the 'zone' argument-

kops create cluster --cloud=vsphere --name=v2c2.skydns.local --zones=vmw-zone --vsphere-server=10.160.236.59 --vsphere-datacenter=VSAN-DC --vsphere-resource-pool=VSAN-Cluster --vsphere-datastore=vsanDatastore --dns=private --vsphere-coredns-server=http://10.160.227.86:2379  --dns-zone=skydns.local --image=ubuntu_16_04 --node-count=2 --networking=flannel --yes

- Checked protokube logs to make sure correct volume data is getting populated, along with etcd cluster information. Here is the log snippet-

I0408 01:00:12.117966       1 vsphere_volume.go:88] Found volumes: [{"ID":"01","LocalDevice":"/dev/sdb1","AttachedTo":"10.160.228.229","Mountpoint":"/mnt/master-01","Status":"attached","Info":{"Description":"main","EtcdClusters":[{"clusterKey":"main","nodeName":"e","nodeNames":["e"]}]}} {"ID":"02","LocalDevice":"/dev/sdc1","AttachedTo":"10.160.228.229","Mountpoint":"/mnt/master-02","Status":"attached","Info":{"Description":"events","EtcdClusters":[{"clusterKey":"events","nodeName":"e","nodeNames":["e"]}]}}]

### CODE REVIEW

**Comment by luomiao** [comment]
LGTM, and sorry you need to rebase :)

**Comment by prashima** [comment]
I am not sure what has happened here. Weren't those changes already part of vsphere-develop?

**Comment by msterin** [comment]
Yes, but the order if commits has changed (to put vendoring upfront) so the commit signatures have changed. Rebase should have no issues and should simply resign your changes on top of latest vsphere -develop

**Comment by prashima** [comment]
Created a new PR after rebasing https://github.com/vmware/kops/pull/46/

**Pull request closed without merging**
